# Generated by Django 4.2.5 on 2023-10-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_forum', '0002_reply_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_to',
        ),
    ]
