# Generated by Django 4.2.5 on 2023-12-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_forum', '0003_remove_reply_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='num_replies',
            field=models.IntegerField(default=0),
        ),
    ]
