# Generated by Django 4.2.6 on 2023-10-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_author_books_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
    ]
