# Generated by Django 4.2.6 on 2023-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(to='main.book'),
        ),
    ]
