# Generated by Django 4.2.5 on 2023-10-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tag_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='books',
        ),
    ]
