# Generated by Django 4.2.6 on 2023-10-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_tag_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(to='main.book'),
        ),
    ]
