# Generated by Django 4.2.6 on 2023-10-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tag_books'),
        ('main', '0010_loggedinuser_delete_user'),
    ]

    operations = [
    ]
