# Generated by Django 4.2.6 on 2023-10-28 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_readinglist_like_comment_book_comments_book_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoggedInUser',
            new_name='Profile',
        ),
    ]
