# Generated by Django 4.2.6 on 2023-10-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_readinglist_like_comment_book_comments_book_likes_and_more'),
        ('main', '0014_rename_loggedinuser_profile'),
    ]

    operations = [
    ]
