# Generated by Django 4.2.6 on 2023-10-28 21:46

from django.db import migrations
from django.core.management import call_command
def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "../fixtures/db.json")

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_20231029_0008'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
