# Generated by Django 4.2.6 on 2023-10-29 06:10

from django.db import migrations
from django.core.management import call_command
def clear_data(apps, schema_editor):
    # Add custom data clearing logic here
    MyModel = apps.get_model('main', 'Book')
    MyModel.objects.all().delete()
    MyModel = apps.get_model('main', 'Tag')
    MyModel.objects.all().delete()
    MyModel = apps.get_model('main', 'Author')
    MyModel.objects.all().delete()

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "../fixtures/db.json")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231029_1235'),
    ]

    operations = [
        migrations.RunPython(clear_data),
        migrations.RunPython(load_my_initial_data),
    ]
