# Generated by Django 4.2.5 on 2023-10-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading_forum.reply'),
        ),
    ]
